### ISSUE TITLE
Create a public gh-pages url

### ISSUE THREAD

**Issue by MollyJameson** [addisonn/gwcFinalProject1#7]
This is a useful tutorial on creating a new branch on the command line:
https://www.thinkful.com/learn/a-guide-to-using-github-pages/start/existing-project/project-page/existing-repo/

When done submit it to Canvas under "Final Project" - level 0

**Comment by lucindaq** [comment]
https://github.io/addisonn/gwcFinalProject1/quiz.html

**Comment by MollyJameson** [comment]
@addisonn was right, the URL is https://addisonn.github.io/gwcFinalProject1/quiz.html

Next week both of you submit this link to canvas.
